### PR TITLE
Add develop files

### PR DESCRIPTION
**Pull request by innocentjr**

### CODE REVIEW

**Comment by innocentjr** [comment]
@tyrrellc just made the pull request.

**Comment by tyrrellc** [comment]
It says that the ENTIRE code file is a conflict.  haha.  ill look at it more tomorrow and try to figure out whats wrong

Colin Tyrrell
MBA / MSI, Class of 2018
Tauber Institute for Global Operations
Ross School of Business
School of Information
University of Michigan
tyrrellc@umich.edu <mailto:tyrrellc@umich.edu>

**Comment by innocentjr** [comment]
@tyrrellc Yeah, the code I added in the new file is nonsense. Just for the purpose of getting the activity done. However, I only added a one line comment on the OAuth file.

**Comment by tyrrellc** [comment]
can you push the oauth file again, but this time put your comment on line 1?  then make pull request

Colin Tyrrell
MBA / MSI, Class of 2018
Tauber Institute for Global Operations
Ross School of Business
School of Information
University of Michigan
tyrrellc@umich.edu <mailto:tyrrellc@umich.edu>

**Comment by innocentjr** [comment]
@tyrrellc there is no need to create another pull request. I made the edit you just send and have pushed it so you should see the change on line one. See commit history

**Comment by tyrrellc** [comment]
awesome. thanks

Colin Tyrrell
MBA / MSI, Class of 2018
Tauber Institute for Global Operations
Ross School of Business
School of Information
University of Michigan
tyrrellc@umich.edu <mailto:tyrrellc@umich.edu>

**Comment by tyrrellc** [comment]
Ok, so we should be good now.  I had to manually remove half of the code  (the merge conflict was just all of your code and followed by all of my code for some reason) and then I made sure both of our comments were at the top.

Colin Tyrrell
MBA / MSI, Class of 2018
Tauber Institute for Global Operations
Ross School of Business
School of Information
University of Michigan
tyrrellc@umich.edu <mailto:tyrrellc@umich.edu>

**Pull request merged**
